### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by orarbel** [AnimaApp/design-token-validator#1]
![image](https://github.com/AnimaApp/design-token-validator/assets/708153/2f13cd04-56cd-4625-a5a1-dfe47cb166c7)

with this input: https://github.com/Sage/design-tokens/blob/master/data/tokens.json

**Comment by andrico-anima** [comment]
Thanks for flagging!

This was resolved with the latest version 🙌🏼

![image](https://github.com/AnimaApp/design-token-validator/assets/119874907/1b9c6029-3682-4bba-a003-b31269cd8495)
